import { z } from "zod";

const envSchema = z.object({
	NEXT_PUBLIC_APP_URL: z.string().url(),
	NEXT_PUBLIC_SUPABASE_URL: z.string().url(),
	NEXT_PUBLIC_SUPABASE_ANON_KEY: z.string().min(10),
	SUPABASE_SERVICE_ROLE_KEY: z.string().min(10),
	NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: z.string().min(10),
	CLERK_SECRET_KEY: z.string().min(10),
	CLERK_WEBHOOK_SECRET: z.string().min(10),
});

export const env = envSchema.parse({
	NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
	NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
	NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
	SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
	NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
	CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
	CLERK_WEBHOOK_SECRET: process.env.CLERK_WEBHOOK_SECRET,
});


